version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "recharts"
        versions: ["3.x"]
    groups:
      shadcn-ui:
        patterns:
          - "@radix-ui/*"
          - "class-variance-authority"
          - "clsx"
          - "lucide-react"
          - "next-themes"
          - "recharts"
          - "sonner"
          - "tailwind-merge"
          -- "tw-animate-css"
      tailwindcss:
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss*"
      vite:
        patterns:
          - "@vitejs/*"
          - "vite*"
          - "vite-plugin-*"
      types:
        patterns:
          - "@types/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
